In [1]:
import probeinterface as pi
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import json

In [2]:
# read probe map json file
probe_map_filename = 'double_sided_probe_map_generated.json'
with open(probe_map_filename, 'r') as f:
    probe_map = json.load(f)
probe_map

{'0': {'mapping': [106,
   111,
   105,
   110,
   104,
   109,
   103,
   108,
   102,
   107,
   101,
   100,
   99,
   98,
   97,
   96,
   122,
   127,
   121,
   126,
   120,
   125,
   119,
   124,
   118,
   123,
   117,
   116,
   115,
   114,
   113,
   112,
   10,
   15,
   9,
   14,
   8,
   13,
   7,
   12,
   6,
   11,
   5,
   4,
   3,
   2,
   1,
   0,
   26,
   31,
   25,
   30,
   24,
   29,
   23,
   28,
   22,
   27,
   21,
   20,
   19,
   18,
   17,
   16,
   90,
   95,
   89,
   94,
   88,
   93,
   87,
   92,
   86,
   91,
   85,
   84,
   83,
   82,
   81,
   80,
   74,
   79,
   73,
   78,
   72,
   77,
   71,
   76,
   70,
   75,
   69,
   68,
   67,
   66,
   65,
   64,
   58,
   63,
   57,
   62,
   56,
   61,
   55,
   60,
   54,
   59,
   53,
   52,
   51,
   50,
   49,
   48,
   42,
   47,
   41,
   46,
   40,
   45,
   39,
   44,
   38,
   43,
   37,
   36,
   35,
   34,
   33,
   32],
  'enabled': [True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True]}}

In [3]:
# gen shank sites
n_channels = 16
y_space = 25/2 # um
x_space = 22.5 # um

y_coords = np.arange(0, n_channels * y_space, y_space)
x_coords = np.zeros(n_channels) # all on the same x position
z_coords = np.zeros(n_channels) # all on the same z position
# offset evens 
x_coords[1::2] = x_space  

assert y_coords[1::2][-1]
shank_df = pd.DataFrame({'x': x_coords, 'y': y_coords, 'z': z_coords})

In [43]:
# create 4 shank probe 
shank_order = ["D_front", "C_front", "B_front", "A_front", "D_back", "C_back", "B_back", "A_back"]
shank_x_offsets = np.arange(0,250*4,250).tolist()*2 # um
probe = []
for shank_i, (shank, offset) in enumerate(zip(shank_order, shank_x_offsets)):
    _shank_df = shank_df.copy()
    _shank_df['x']+= offset
    _shank_df['shank_ids'] = shank_i

    probe.append(_shank_df)
probe = pd.concat(probe, ignore_index=True)
probe.loc[:64,'z'] += 25 # um
probe

         x      y     z  shank_ids
0      0.0    0.0  25.0          0
1     22.5   12.5  25.0          0
2      0.0   25.0  25.0          0
3     22.5   37.5  25.0          0
4      0.0   50.0  25.0          0
..     ...    ...   ...        ...
123  772.5  137.5   0.0          7
124  750.0  150.0   0.0          7
125  772.5  162.5   0.0          7
126  750.0  175.0   0.0          7
127  772.5  187.5   0.0          7

[128 rows x 4 columns]

In [67]:
# set pi probe
p1d = pi.Probe(ndim=3, si_units='um')
p1d.set_contacts(probe[['x','y','z']],plane_axes='xy',shapes='rect', shape_params={'width':11.0, 'height': 15.0})
p1d.set_shank_ids(probe['shank_ids'].values)
p1d.set_contact_ids(probe.index.values+1)
pi.write_probeinterface('ASSY-325-P-1-D.json', p1d)

In [ ]:
p1d.to_dataframe().tail(10)

         x      y    z contact_shapes  width  height shank_ids contact_ids
118  750.0   75.0  0.0           rect   11.0    15.0         7         119
119  772.5   87.5  0.0           rect   11.0    15.0         7         120
120  750.0  100.0  0.0           rect   11.0    15.0         7         121
121  772.5  112.5  0.0           rect   11.0    15.0         7         122
122  750.0  125.0  0.0           rect   11.0    15.0         7         123
123  772.5  137.5  0.0           rect   11.0    15.0         7         124
124  750.0  150.0  0.0           rect   11.0    15.0         7         125
125  772.5  162.5  0.0           rect   11.0    15.0         7         126
126  750.0  175.0  0.0           rect   11.0    15.0         7         127
127  772.5  187.5  0.0           rect   11.0    15.0         7         128

In [50]:
p464_probe = pi.get_probe('cambridgeneurotech','ASSY-236-P-1')
p464_probe.to_dataframe('full').tail(10)

,x,y,contact_shapes,width,height,shank_ids,contact_ids,device_channel_indices,si_units,plane_axis_x_0,plane_axis_x_1,plane_axis_y_0,plane_axis_y_1
54,500.0,50.0,rect,11.0,15.0,2,55,-1,um,1.0,0.0,0.0,1.0
55,522.5,112.5,rect,11.0,15.0,2,56,-1,um,1.0,0.0,0.0,1.0
56,250.0,50.0,rect,11.0,15.0,1,57,-1,um,1.0,0.0,0.0,1.0
57,250.0,125.0,rect,11.0,15.0,1,58,-1,um,1.0,0.0,0.0,1.0
58,22.5,112.5,rect,11.0,15.0,0,59,-1,um,1.0,0.0,0.0,1.0
59,22.5,187.5,rect,11.0,15.0,0,60,-1,um,1.0,0.0,0.0,1.0
60,0.0,100.0,rect,11.0,15.0,0,61,-1,um,1.0,0.0,0.0,1.0
61,0.0,25.0,rect,11.0,15.0,0,62,-1,um,1.0,0.0,0.0,1.0
62,0.0,0.0,rect,11.0,15.0,0,63,-1,um,1.0,0.0,0.0,1.0
63,0.0,175.0,rect,11.0,15.0,0,64,-1,um,1.0,0.0,0.0,1.0