In [5]:
import probeinterface as pi
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import json

In [6]:
# read probe map json file
probe_map_filename = 'double_sided_probe_map_generated.json'
with open(probe_map_filename, 'r') as f:
    probe_map = json.load(f)
probe_map

{'0': {'mapping': [106,
   111,
   105,
   110,
   104,
   109,
   103,
   108,
   102,
   107,
   101,
   100,
   99,
   98,
   97,
   96,
   122,
   127,
   121,
   126,
   120,
   125,
   119,
   124,
   118,
   123,
   117,
   116,
   115,
   114,
   113,
   112,
   10,
   15,
   9,
   14,
   8,
   13,
   7,
   12,
   6,
   11,
   5,
   4,
   3,
   2,
   1,
   0,
   26,
   31,
   25,
   30,
   24,
   29,
   23,
   28,
   22,
   27,
   21,
   20,
   19,
   18,
   17,
   16,
   90,
   95,
   89,
   94,
   88,
   93,
   87,
   92,
   86,
   91,
   85,
   84,
   83,
   82,
   81,
   80,
   74,
   79,
   73,
   78,
   72,
   77,
   71,
   76,
   70,
   75,
   69,
   68,
   67,
   66,
   65,
   64,
   58,
   63,
   57,
   62,
   56,
   61,
   55,
   60,
   54,
   59,
   53,
   52,
   51,
   50,
   49,
   48,
   42,
   47,
   41,
   46,
   40,
   45,
   39,
   44,
   38,
   43,
   37,
   36,
   35,
   34,
   33,
   32],
  'enabled': [True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True]}}

In [9]:
# gen shank sites
n_channels = 16
y_space = 25/2 # um
x_space = 22.5 # um

y_coords = np.arange(0, n_channels * y_space, y_space)
x_coords = np.zeros(n_channels) # all on the same x position
z_coords = np.zeros(n_channels) # all on the same z position
# offset evens 
x_coords[1::2] = x_space  

assert y_coords[1::2][-1]
pd.DataFrame({'x': x_coords, 'y': y_coords, 'z': z_coords})

       x      y    z
0    0.0    0.0  0.0
1   22.5   12.5  0.0
2    0.0   25.0  0.0
3   22.5   37.5  0.0
4    0.0   50.0  0.0
5   22.5   62.5  0.0
6    0.0   75.0  0.0
7   22.5   87.5  0.0
8    0.0  100.0  0.0
9   22.5  112.5  0.0
10   0.0  125.0  0.0
11  22.5  137.5  0.0
12   0.0  150.0  0.0
13  22.5  162.5  0.0
14   0.0  175.0  0.0
15  22.5  187.5  0.0

In [ ]:
# create 4 shank probe